# Generated by Django 3.1.6 on 2021-02-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottage',
            name='slug',
            field=models.SlugField(default='jan', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
