# Generated by Django 3.1.6 on 2021-02-19 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210219_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottage',
            name='transport_price',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cottagephoto',
            name='cottage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cottage_photos', to='core.cottage'),
        ),
        migrations.CreateModel(
            name='OptionalServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cottage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cottage')),
            ],
        ),
    ]
