# Generated by Django 3.1.6 on 2021-02-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210219_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionalservices',
            name='name',
            field=models.CharField(choices=[('MO', 'Montaż'), ('MA', 'Malowanie'), ('OK', 'Okiennice'), ('RY', 'Rynny'), ('KP', 'Krycie dachu papą'), ('KG', 'Krycie dachu gontem'), ('KB', 'Krycie dachu blachodachówką'), ('OP', 'Ocieplenie podłogi'), ('OS', 'Ocieplenie ścian'), ('OD', 'Ocieplenie dachu')], default=None, max_length=40),
            preserve_default=False,
        ),
    ]
