# Generated by Django 3.1.6 on 2021-02-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210219_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottage',
            name='additionals',
            field=models.ManyToManyField(blank=True, null=True, to='core.Additional'),
        ),
        migrations.AlterField(
            model_name='optionalservice',
            name='name',
            field=models.CharField(choices=[('MO', 'Montaż'), ('MA', 'Malowanie'), ('OK', 'Okiennice'), ('RY', 'Rynny'), ('KP', 'Krycie dachu papą'), ('KG', 'Krycie dachu gontem'), ('KB', 'Krycie dachu blachodachówką'), ('OP', 'Ocieplenie podłogi'), ('OS', 'Ocieplenie ścian'), ('OD', 'Ocieplenie dachu'), ('TK', 'Tynkowanie')], max_length=40),
        ),
    ]
