# Generated by Django 3.1.6 on 2021-02-19 10:51

import core.models
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210211_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottage',
            name='description',
            field=tinymce.models.HTMLField(default=20.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cottage',
            name='height',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cottage',
            name='length',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cottage',
            name='width',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cottagephoto',
            name='image',
            field=models.ImageField(upload_to=core.models.cottage_directory_path),
        ),
    ]
