# Generated by Django 3.1.6 on 2021-02-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210219_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='cottage',
            name='floor_area',
            field=models.DecimalField(decimal_places=2, default=20.2, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cottage',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cottage',
            name='width',
            field=models.IntegerField(),
        ),
    ]
