# Generated by Django 3.1.6 on 2021-02-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_optionalservices_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OptionalServices',
            new_name='OptionalService',
        ),
    ]
