# Generated by Django 3.1.6 on 2021-03-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210223_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cottage',
            name='additionals',
            field=models.ManyToManyField(blank=True, to='core.Additional'),
        ),
    ]
